"""Initial schema with all columns

Revision ID: d0831123c905
Revises: 5e7961e16dc3
Create Date: 2026-03-03 10:49:54.627079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0831123c905'
down_revision: Union[str, Sequence[str], None] = '5e7961e16dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_food_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('effect_stat', sa.String(length=20), nullable=False),
    sa.Column('effect_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('pet_food_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_food_items_id'), ['id'], unique=False)

    op.create_table('feeding_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('fed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['pet_food_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feeding_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feeding_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feeding_logs_user_id'), ['user_id'], unique=False)

    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('quality', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_logs_user_id'), ['user_id'], unique=False)

    op.create_table('workout_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=100), nullable=False),
    sa.Column('muscle_group', sa.String(length=50), nullable=True),
    sa.Column('duration_mins', sa.Float(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_logs_id'))

    op.drop_table('workout_logs')
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_meal_logs_id'))

    op.drop_table('meal_logs')
    with op.batch_alter_table('feeding_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feeding_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_feeding_logs_id'))

    op.drop_table('feeding_logs')
    with op.batch_alter_table('pet_food_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_food_items_id'))

    op.drop_table('pet_food_items')
    # ### end Alembic commands ###
